language: python
before_install:
  - wget -O tests/consul_1.6.1_linux_amd64.zip https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_amd64.zip
  - wget -O tests/consul_1.6.1_linux_arm64.zip https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_arm64.zip
  - cd tests
  - unzip consul_1.6.1_linux_amd64.zip
  - mv consul consul.linux64
  - unzip consul_1.6.1_linux_arm64.zip
  - mv consul consul.aarch64
  - cd ..

git:
  lfs_skip_smudge: true

arch:
  - amd64
  - arm64

python:
  - "2.7"
  - "pypy"
  - "pypy3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

matrix:
  allow_failures:
    - python: 3.7-dev
    - python: 3.8-dev
    - python: nightly
    - python: pypy3


install:
  - pip install tox
  - pip install tox-travis
script:
  - tox

jobs:
  include:
    - stage: sonar
      git:
        lfs_skip_smudge: true
      dist: xenial
      language: python
      python: '3.7'
      addons:
        sonarcloud:
          organization: python-consul2
          token:
            secure: "sDDl1BmJbd5viFM67qNeEOKoN57IzVmAKDNBJV/HvwtjzFc9SQPgkM7SyyFBL5TWT5TZ9CIMV8gsS6Knu25pt1L4uEDCLWwGtz/Ha7xNCmmV8JlTc085EDv8wBqoitXiWYp4WJtkxxB3LZRECRFpL72H10QQHOttUs5PGEBLhb1QbkoAFGftnO44CWYygfUlgZCgx+aHfm5vAQM5HSmRrJCYKLMPjtERnsA521sspWOM8wKpJw+EZ+fMdcqL2bGKCfe3gQ7VFa39fQ1IDoZki5Xlu1Mxgwg6OTcbTcIh4JknvLNqAKkKQwk4VkovE5vKNwWgVvL0F81Os/PsLSXgyF2tOz7o3Upp1QeoXleH4Vyj94Z37ktd967oT/c7OierA6QFJey2/tc/PVzcE8B919ud6HPYVblSAaGAg3r4cBVtolFv/kwIUQWvGMxsjPNnci6eQ5vXEFGb16BHgB33zmqPif8kg+8+8cehSi84aFb44ZTDzqW6ew4oOwzIvi9fmYWwX1GzYS3/nK1clJKSX9ypWhW/bqM1e7eHm0lsGM2WSZZ8OORCnx9QVv0BRnigtRwAfeaV1iwDHDNczMdXyOL6im5i9kipiKEZ2DZOz+WJOtw/zBU/ISX7nau20crMCxFdyqgWKEpJOuxZZA++kfXi1MxcBXgSf/FxfT4mMmQ="
          branches:
            - master
      install: ignore
      script:
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi
      branches:
        only:
          - master


    - stage: deploy
      script: ignore
      python: '3.7'
      deploy:
        provider: pypi
        user: poppys
        password:
          secure: JVQo2ufR1pJD9AtpNuLsHNKzT7tvpCOQ3bAp3eOm8Hvk0XrInB1G+mChC7cx+gfQ6yAddRI4YjeDBbi2ZO1m/HZecQpizaiPSrkiBkeqwbSWHLwMu0DeC4Tlfy17wfrnqPjyoYlY4pXLhOl32YYnWDGGEn46wPNYcZAPp6UL6GN8jY3HjbYdYZ9xej58/pb8LvqlvCjCA5oXor2QaRLof5tlj8ZflwPW4vx8GSDej9vpXSu3vQFhM3qStLS8ew9yjVPsnIpDSDOVn13xC3hD8Xmk2YOjDEnFfi8RA+cWuoTj0pN7E6fqgCtM3gGuAe3gqj47d0G1segtVJ2qxXvuITV9RJ6zkwzRs/s3xwFSEX+7OXR4UVrwl3heHykggIqHCPHBJIbh3QtniyRCp5kH4VmAH/7q09HCFNVZVfgvN7E8BbaNSoDl6WA0ndEcsv8PJhQYa4LcqR1nbuOPbkx7QxmCEyI6yKfKkMiuOEvrnOU8ONYzvVtKo1MxR+YaLVkKrgwj1V/URUevvRQztiaNiD1yDzaCOAPqfR2VwuB2BsVaVV5SE3Md2IjCmr4vvuj11h1EJ4qOi0BpmCmW+1aWBlsOVEamNbhxFQ7hTl+GtbHOEGb8r6GlO9xDIM0rNOYjm9MU1qjuTfGmqttwAR46xIhNskHRXzN5SVz6SAV0uGw=
        on:
          tags: true

    - stage: codecov
      python: '3.7'
      install:
        - pip install coverage pytest codecov pytest-cov  pytest-rerunfailures pytest-twisted twisted treq pytest_httpserver pyOpenSSL tornado aiohttp
      script:
          - py.test --cov-report=xml --cov=consul tests/
          - codecov


