name: python-consul2 ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python: [2.7, 3.5, pypy2, pypy3, 3.5, 3.6, 3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: dowload consul bin files
        run: |
            wget -O tests/consul_1.6.1_linux_amd64.zip https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_amd64.zip
            wget -O tests/consul_1.6.1_linux_arm64.zip https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_arm64.zip
            cd tests
            unzip consul_1.6.1_linux_amd64.zip
            mv consul consul.linux64
            unzip consul_1.6.1_linux_arm64.zip
            mv consul consul.aarch64
            cd ..

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Tox and any other packages
        run: pip install tox

      - name: Run Tox
        run: tox -e py  # Run tox using the version of Python in `PATH`
